
package com.tdcare.bom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_DataInterchangeServiceSoap", targetNamespace = "http://www.tdcare.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSDataInterchangeServiceSoap {


    /**
     * 
     * @param iCMDType
     * @param iData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DataInterchange", action = "http://www.tdcare.com/DataInterchange")
    @WebResult(name = "DataInterchangeResult", targetNamespace = "http://www.tdcare.com/")
    @RequestWrapper(localName = "DataInterchange", targetNamespace = "http://www.tdcare.com/", className = "com.tdcare.DataInterchange")
    @ResponseWrapper(localName = "DataInterchangeResponse", targetNamespace = "http://www.tdcare.com/", className = "com.tdcare.DataInterchangeResponse")
    public String dataInterchange(
        @WebParam(name = "iCMDType", targetNamespace = "http://www.tdcare.com/")
        String iCMDType,
        @WebParam(name = "iData", targetNamespace = "http://www.tdcare.com/")
        String iData);

}
