
package com.tdcare.bom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_DataInterchangeService", targetNamespace = "http://www.tdcare.com/", wsdlLocation = "https://telehealth.foracare.com/WebService/WS_DataInterchangeService.asmx?WSDL")
public class WSDataInterchangeService
    extends Service
{

    private final static URL WSDATAINTERCHANGESERVICE_WSDL_LOCATION;
    private final static WebServiceException WSDATAINTERCHANGESERVICE_EXCEPTION;
    private final static QName WSDATAINTERCHANGESERVICE_QNAME = new QName("http://www.tdcare.com/", "WS_DataInterchangeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://telehealth.foracare.com/WebService/WS_DataInterchangeService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDATAINTERCHANGESERVICE_WSDL_LOCATION = url;
        WSDATAINTERCHANGESERVICE_EXCEPTION = e;
    }

    public WSDataInterchangeService() {
        super(__getWsdlLocation(), WSDATAINTERCHANGESERVICE_QNAME);
    }

    public WSDataInterchangeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDATAINTERCHANGESERVICE_QNAME, features);
    }

    public WSDataInterchangeService(URL wsdlLocation) {
        super(wsdlLocation, WSDATAINTERCHANGESERVICE_QNAME);
    }

    public WSDataInterchangeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDATAINTERCHANGESERVICE_QNAME, features);
    }

    public WSDataInterchangeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDataInterchangeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSDataInterchangeServiceSoap
     */
    @WebEndpoint(name = "WS_DataInterchangeServiceSoap")
    public WSDataInterchangeServiceSoap getWSDataInterchangeServiceSoap() {
        return super.getPort(new QName("http://www.tdcare.com/", "WS_DataInterchangeServiceSoap"), WSDataInterchangeServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDataInterchangeServiceSoap
     */
    @WebEndpoint(name = "WS_DataInterchangeServiceSoap")
    public WSDataInterchangeServiceSoap getWSDataInterchangeServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tdcare.com/", "WS_DataInterchangeServiceSoap"), WSDataInterchangeServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDATAINTERCHANGESERVICE_EXCEPTION!= null) {
            throw WSDATAINTERCHANGESERVICE_EXCEPTION;
        }
        return WSDATAINTERCHANGESERVICE_WSDL_LOCATION;
    }

}
